### ISSUE TITLE
Arabic reflow document seems correctly paginated, but displays only last pages

### ISSUE THREAD

**Issue by danielweck** [readium/SDKLauncher-iOS#34]
Test EPUB:
https://code.google.com/p/epub-samples/downloads/detail?name=regime-anticancer-arabic-20130327.epub

Note that Japanese RTL page progression direction with vertical writing mode works fine:
https://code.google.com/p/epub-samples/downloads/detail?name=kusamakura-japanese-vertical-writing-20121124.epub

Suggestion: check this code https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L234

**Comment by rkwright** [comment]
Retested by Olivier and Ric.  Not reproducible/  Closing
