### ISSUE TITLE
epub looks and work perfect in chrome plugins, does not work on IOS

### ISSUE THREAD

**Issue by OmarCur** [readium/SDKLauncher-iOS#37]
Hi there,

We are working and testing the Readium project. We are using the Chrome plugin to test an epub3.

This epub is exported from indesign cc2014 (latest build), it looks perfect in windows/chrome/readium plugin.

we have build our own app for iOs and there are a ton of issues, i hope you can explain and /or help us.

First of all if we leave the TOC generation on in Indesign the ePub crashes, if we switch it to TOC - filename it works.

Most fonts do not look correct on IOS, they do look correctly on the chrome plugin.

We have a Epub 3 file, full of interactive animations made in Adobe Edge, these animations need to go inside the Indesign document,

These animations work in the chrome plugin and in the Gitden IOS reader but do not in the readium IOS versions.

We really want to have a good reader for these complex epub files, please help or steer us in the right directions.

Thanks.

O. Curiere
OCG Studios
info@ocgstudios.com

**Comment by Sptibo** [comment]
Hi Daniel,
I've cloned ReadiumSDKLauncher and test it in my device by importing .epub file. It is working. Now I want to integrate the launcher on my existing project. I used the carthage file for the implementation of the dependencies. There are R2Shared.framework and other frameworks. But in ReadiumSDKLauncher there are RDServices folder and Viewcontroller classes too. I do not know how to integrate this launcher on my existing project. Could you please tell me something about those sdks?

**Comment by rkwright** [comment]
@Sptibo Can you outline what you are ultimately trying to do?  Are you trying to build a R1-SDK application or an R2-based application?  Can you tell us what you are trying to achieve?

**Comment by Sptibo** [comment]
@rkwright I've downloaded R2-based dependencies. I have some kind of CCID of books got from URMS SDK and now want to read that book using Readium. 
Firstly I clone Readium sdk launcher, copy .epub file on device and open that with readium.
Then I download readium sdk and include them in my existing project
Please guide ma how do I use those sdks in my project in order to read books.

**Comment by danielweck** [comment]
This repository (SDKLauncher-iOS) demonstrates how to integrate readium-shared-js and readium-sdk which are Readium "1" projects. It seems you are trying to integrate Readium2 components, which is probably not going to work. There are "launcher" apps (aka "test apps") for each Readium2 target platform: iOS-Swift, Android-Kotlin, desktop-Electron/NodeJS (Linux, Windows, MacOS). You should focus your efforts on either R1 or R2, as the projects were never really intended for "hybrid" applications. My knowledge of URMS is only superficial. I think there are existing ReadiumSDK (Readium "1") integrations, perhaps @aferditamuriqi can provide some guidance? Readium apps are LCP-ready, and in principle other DRM schemes are supported too (although at this point in time I am not aware of any existing practical implementation). I hope this helps.

**Comment by Sptibo** [comment]
@danielweck I am trying to use r2-testapp-swift as a template and modify it. Is that a better way to do? Because I do not understand how to integrate and implement those sdks on existing project. Can you provide me a good documentation (with step wise description) to integrate r2 in my project. Or I have to pay you for support?

**Comment by danielweck** [comment]
Could you please file an issue at r2-testapp-swift, this would be more appropriate. Thanks!
