### ISSUE TITLE
MathJax icons are missing from single-file build (Base64, or need to include actual image files?)

### ISSUE THREAD

**Issue by wzhsunn** [readium/SDKLauncher-iOS#49]
2015-03-10 20:17:04.971 SDKLauncher-iOS[6026:61ab] The resource content length is zero! images/CloseX-31.png

epub file :
https://github.com/IDPF/epub3-samples/tree/master/30/linear-algebra/EPUB

**Comment by danielweck** [comment]
Thank you for reporting this @wzhsunn 

The missing icon image is actually requested by the MathJax MathML rendering library (not the EPUB sample itself):
https://github.com/mathjax/MathJax/blob/master/images/CloseX-31.png

It would seem that the MathJax single-file library that is built specifically for Readium actually requires external files too (well, at least these particular icon images `CloseX-31.png` and  `MenuArrow-15.png`). 

See here for details about the MathJax library build:
https://github.com/readium/readium-js-viewer/issues/262

@pkra what do you think? Can these asset dependencies be encoded and bundled as Base64 (which would be our preferred option), or do we have to copy them across into each Readium launcher app repository? (which would require some adaptation of the asset provider interface, to supply external files that are not actually contained within the EPUB document filesets, but instead located at the app level)

I see this in the MathJax code:
(single library file: https://raw.githubusercontent.com/readium/readium-js-viewer/develop/lib/mathjax/MathJax.js )
```javascript
imageDir:
e + ( b.isPacked ? "" : "/.." ) + "/images"
```
Originally from:
`MathJax.js`: https://github.com/mathjax/MathJax/blob/master/MathJax.js
`CloseX-31.png` example usage:
`HelpDialog.js`: https://github.com/mathjax/MathJax/blob/master/extensions/HelpDialog.js
`MathMenu.js`: https://github.com/mathjax/MathJax/blob/master/extensions/MathMenu.js

And I found this reference in the issue tracker: https://github.com/mathjax/MathJax/issues?q=CloseX-31.png
(PNG compression)

...so I guess the Base64 option is not available / has not been requested so far?

Thanks a lot!
Dan

**Comment by wzhsunn** [comment]
I need a feature to support mathml.
As [this](http://docs.mathjax.org/en/latest/misc/epub.html)  said :

name|via
-------|-------
iBooks|via mobile Safari
Readium|iOS: via mobile Safari, web-based: via MathJax

I found iBooks  supports well  and faster but readium a little slow.

Dose readium-ios support mathml via mathjax  or  mobile safari ?

**Comment by danielweck** [comment]
By default, all configurations of Readium (cloud reader / Chrome extension + native launchers on iOS, OSX, Android, and someday Windows) use MathJax to render MathML markup.
However, Readium vendors / integrators may decide to opt-out of MathJax (e.g. instead, rely on the web view / web browser "native" capabilities).
The current MathJax configuration for Readium uses the SVG render path, for reasons detailed here (mostly: no dependency on external fonts): https://github.com/readium/readium-js-viewer/issues/262

**Comment by pkra** [comment]
@danielweck I've opened https://github.com/mathjax/MathJax/issues/1088  (which I should've done a while ago, oh well).

**Comment by danielweck** [comment]
Great, thanks @pkra :)

**Comment by danielweck** [comment]
By the way, the MathJax devs fixed this: https://github.com/mathjax/MathJax/issues/1088
This is part of Milestone 2.6: https://github.com/mathjax/MathJax/milestones
(at Readium, we have yet to merge v2.5, see https://github.com/readium/readium-js-viewer/issues/262 )

**Comment by rkwright** [comment]
Probably fixed by MathJax 2.6.  Need to retest.

**Comment by danielweck** [comment]
Fixed.

iOS:
https://github.com/readium/SDKLauncher-iOS/commit/ec6ed17fe6f3add917f9557de59beb7f5009072b

Android:
https://github.com/readium/SDKLauncher-Android/commit/d1e98924d397a58f11d0e5b83258024cd171859f

OSX:
https://github.com/readium/SDKLauncher-OSX/commit/d96e02450e28d8e0fa72aa70c8bcf12b74cb881c

Cloud reader test URL (Chrome app uses the same NPM-fetched MathJax dependency):
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub-testsuite%2Fmaster%2Fcontent%2F30%2Fepub30-test-0100&goto=%7B%22idref%22%3A%22xhtml-mathml-001%22%7D

https://github.com/readium/readium-js-viewer/blob/develop/package/package_base.cson#L132
https://github.com/pkra/MathJax-single-file
