### ISSUE TITLE
app lacks "about page" info

### ISSUE THREAD

**Issue by duanwalker** [readium/SDKLauncher-iOS#51]
in an attempt to verify the version being tested, i cannot confirm as there is no about or info page.

**Comment by danielweck** [comment]
Correct. There is no "version info" User Interface as far as I know.
Please load the bundled EPUB to display detailed reading system information:
https://github.com/readium/SDKLauncher-iOS/blob/master/Resources/epubReadingSystem.epub

**Comment by duanwalker** [comment]
understood.
will do. thanks

**Comment by rkwright** [comment]
Closing as answered.
