### ISSUE TITLE
Cannot build on Yosemite with Xcode 7.2

### ISSUE THREAD

**Issue by kjantzer** [readium/SDKLauncher-iOS#69]
Has anyone been able to build lately?

I get the following error:

![screen shot 2015-12-29 at 11 51 31 am](https://cloud.githubusercontent.com/assets/467487/12041020/8938ccf0-ae22-11e5-8e89-3dadc64dcb1b.png)

**Comment by jdempcy** [comment]
I'm on El Capitan and Xcode 7.1.1.

I'll upgrade to Xcode 7.2 and see if I can repro (understanding, of course, I'm on a different operating system revision.)

Any special repro steps or just grab latest master of SDKLauncher-iOS and follow the readme?

**Comment by kjantzer** [comment]
I just cloned the master repo then tried to build.

**Comment by jdempcy** [comment]
Okay, I'll try that also. Upgrading to Xcode 7.2 now.

One thing to try: when I clone I make sure to add the --recursive flag so it gets all submodules. If this flag wasn't present then I don't think it would pull down the readium-sdk submodule that it needs:

https://github.com/readium/readium-sdk

Maybe you could try "git submodule update --init --recursive" from the root of where you cloned the SDKLauncher-iOS project? I'm not sure if this would pull in the submodule if it wasn't cloned recursively to begin with, however.

Or, if you already have the submodule, ignore this comment!

**Comment by rkwright** [comment]
I just cloned master and built with XCode7.2 on El Capitan.  No errors and it launched fine on my iPad.

**Comment by kjantzer** [comment]
Ok, thanks @rkwright . Maybe I'm missing something in my development environment. I'm thinking of using [FolioReader](https://github.com/FolioReader/FolioReaderKit) instead though.

**Comment by danielweck** [comment]
Hello, is zsh installed on your machine, and accessible from your terminal / shell command line? See the script's first line:
https://github.com/readium/readium-sdk/blob/develop/Platform/Apple/MakeHeaders.sh

Can you build from the develop branch?

**Comment by kjantzer** [comment]
@danielweck `zsh` is installed and yes, I was able to access it from the CLI, which is one of the reasons I was surprised it didn't build.

I have not tried the develop branch.

**Comment by rkwright** [comment]
Closing as not reproducible
