### ISSUE TITLE
Encoding issues with some EPUBs on iOS

### ISSUE THREAD

**Issue by olivierkorner** [readium/SDKLauncher-iOS#71]
Non-ASCII characters are rendered wrong, as if UTF-8 file was read as Latin-1.
I can provide a book for testing (by email olivierkorner@artbookmagazine.com).

The book is displayed correctly Chrome.
Adding `<meta charset="UTF-8">` to the reader html file seems to solve the problem though...

![readium-ios-encoding-issue](https://cloud.githubusercontent.com/assets/587255/12920718/fc94524e-cf49-11e5-970d-e2fccc87a559.png)

**Comment by danielweck** [comment]
Hello @olivierkorner yes please, send me the EPUB via email. Thanks!

**Comment by rkwright** [comment]
@olivierkorner  Can you share the book with us? Is the font embedded in the EPUB or is it being loaded from the system?

**Comment by olivierkorner** [comment]
Hello,
Here’s the file. No embedded fonts…

**Comment by danielweck** [comment]
@olivierkorner where is the EPUB file? (missing attachment?)

**Comment by danielweck** [comment]
I am able to reproduce this bug in OSX. I will look into it.

**Comment by rkwright** [comment]
I also reproduced on iOS and OSX but it is NOT present in the Chrome Extension (2.22.2).  I'll try Android next, just to see,

**Comment by rkwright** [comment]
The problem does not occur with the current (0.23-alpha) build on Android using my Nexus 7 with Marshmallow.

**Comment by danielweck** [comment]
Thank you @olivierkorner for your tip about `<meta charset="UTF-8">` in reader.html (single, multiple RequireJS bundles etc.)
I verified other potential causes for the encoding mismatch, to no avail. Your simple trick works in OSX (I haven't tried iOS, but it looks like you checked yourself).

**Comment by olivierkorner** [comment]
@danielweck Yes, tested on iOS

**Comment by msintov** [comment]
Thank you for this post!! Fixed for me on iOS too.

**Comment by danielweck** [comment]
Fixed in iOS:
https://github.com/readium/SDKLauncher-iOS/commit/8acd4522b4fa11a346ae8a37cf3ad85045d8654a

Fixed in OSX:
https://github.com/readium/SDKLauncher-OSX/commit/16bb86c92b34e3b0bf21d79ebbb3098b20f400e0

**Comment by danielweck** [comment]
Addressed in Android too, to prevent future issues because of the missing meta UTF8 charset tag:
https://github.com/readium/SDKLauncher-Android/commit/49734b29238c969c21643d80aeee05e36ba1035a
