### ISSUE TITLE
Load One Page in WebView instead of complete epub.

### ISSUE THREAD

**Issue by majidtbox** [readium/SDKLauncher-iOS#73]
Hi @danielweck 

I am using readium iOS SDK in my app. I want to load one page at a time instead of loading complete epub in a webview to save loading time. I have looked into this branch: https://github.com/readium/readium-shared-js/tree/feature/prefetch
that you mentioned here: https://github.com/readium/SDKLauncher-iOS/issues/72 but it didn't solve my problem. It is only preventing memory leaks. Please guide me how I can load a single page for a webview to save loading time. I will be waiting for your response.

Thanks

**Comment by majidtbox** [comment]
Hi @danielweck 

Please guide me for above mentioned issue. I will be waiting for your response.

Thanks.

**Comment by danielweck** [comment]
Hello, I am afraid there is no such feature in Readium. I replied here as well, so I am closing this issue.
https://github.com/readium/SDKLauncher-iOS/issues/72#issuecomment-206129035
