### ISSUE TITLE
SDK Launcher- ios 

### ISSUE THREAD

**Issue by sharak16** [readium/SDKLauncher-iOS#84]
Hi @rkwright , can you help me to use 
 " SDK Launcher- ios " as library  in our IOS-Project.

Currently for development below environment i m following:-
xcode version -7.3.1
mac version-10.11.2

**Comment by sharak16** [comment]
I just want to use SDK-Launcher same as android , because as of i know in android environment we could import whole package in our project and can call the functions Readium .But we can't do the same in ios please suggest how could we achieve the same in ios ?

**Comment by danielweck** [comment]
Moved: https://github.com/readium/readium-sdk/issues/265
