### ISSUE TITLE
Regarding exporting of annotations to our backend server.

### ISSUE THREAD

**Issue by Dchahar** [readium/SDKLauncher-iOS#85]
We want to use it in iOS with your SDK. Please tell following can be achieved or not? And how complex is the implementation? 

1. To fetch all the annotation from readium so that we can send it to our server.
2. Open particular page and chapter while opening ebook. So that book is open from last viewed page.
3. To see all the notes in on single view and jump to that highlighted part of the book.

**Comment by danielweck** [comment]
2 is already implemented in readium-js-viewer, using the readium-shared-js reader_view.js "get bookmark" feature, so this technique can be used in a native app too (note that the ReadiumSDK "launchers" are deliberately basic apps, so please do not expect a full-feature polished user experience).

**Comment by danielweck** [comment]
Regarding 1, Readium does not produce "annotations" per-se, but there is indeed an experimental plugin for text selection and highlighting. There is currently no built-in support for persistent storage of content highlights.

**Comment by danielweck** [comment]
3 is a useful and important feature, but the current text selection / highlighting plugin is experimental so the implementation would need to be written by a Readium contributor. Also note that such feature is unlikely to make its way into the native app launchers, as these are intentionally kept simple (Readium vendors add their own sophisticated features).
