### ISSUE TITLE
ePubLibrary view with cover image

### ISSUE THREAD

**Issue by pervy-sage** [readium/SDKLauncher-iOS#87]
The readium SDK is excellent for ios and is ideal for creating a space for our ePubs. I was curious if anybody had created a branch/version of the ios sdk that allows epubs to be viewed in a library style gallery. One that is similar to the readium library found in the web-app or the chrome app.
Thanks

**Comment by danielweck** [comment]
This would typically be a product differentiator (unique selling point) for vendors who adopt ReadiumSDK as their eBook rendering engine, so I doubt there are open-source off-the-shelf library UI components available right now.
However, NYPL opened a lot of its code, so maybe that's a good place to ask?
https://github.com/NYPL-Simplified

**Comment by pervy-sage** [comment]
Thanks, I don’t think it would be that difficult to create a library view for iOS. I’ll give it a shot and see how I go.
 <http://www.buildaustralia.com.au/>  <http://www.buildaustralia.com.au/> <http://www.buildaustralia.com.au/> <http://www.buildaustralia.com.au/>

**Comment by danielweck** [comment]
That would be great, thank you!
