### ISSUE TITLE
Errors with Book Marks

### ISSUE THREAD

**Issue by pervy-sage** [readium/SDKLauncher-iOS#88]
Hey Guys,

So while working on the SDK launcher for ios i noticed the book mark settings arent working. Im pretty sure I have the latest version of the SDK launcher from github. The bug in question occurs when I try to create a bookmark on any page. Ive tried this with several different e-pubs on different pages all with the same result. Trying to add a bookmark, invokes this message from NSLog: `SDKLauncher-iOS[2899:469264] -[NSNull length]: unrecognized selector sent to instance 0x3a60238
(lldb)` 

Any help will be appreciated.

Thanks

**Comment by rkwright** [comment]
@pervy-sage What bookmarking code are you using?  The bookmark plugin sample from Readium?

**Comment by pervy-sage** [comment]
Hi Ric,

Im using the code that came with the readium sdk launcher sample. The error occurs in bookmark.m. When I try and create a book mark an error comes up saying that one of the variables are not recognised. The variable is cfi which is a pointer to kKeyCFI : m_cfi. There error code is in my previous message. Im slowly trying to break down the code and understand it. I think I know what might be wrong but I’ll have to do a few more tests.


ZAYD BHYAT 
I.T SUPPORT OFFICER

**Comment by pervy-sage** [comment]
I also apologize for the late reply as I am based in Australia.
:D

ZAYD BHYAT 
I.T SUPPORT OFFICER

**Comment by pervy-sage** [comment]
Update: When no bookmark title is entered the application crashes.

**Comment by pervy-sage** [comment]
Update: In an attempt to fix something I thought was wrong with the framework I neglected to look at the ePubs I was testing. I am unable to emulate the above issue so it can be closed
