### ISSUE TITLE
some errors about “Platform” namespace

### ISSUE THREAD

**Issue by CJCX** [readium/SDKLauncher-iOS#95]
when i use the sdk in my work ,some errors here,what can i do?

/Users/songsipeng/Desktop/cp/hdsDesktop201605303/hdsDesktop/readium-sdk/Platform/WinRT/Readium/Readium/Readium.h:40:19: No member named 'Platform' in the global namespace

/Users/songsipeng/Desktop/cp/hdsDesktop201605303/hdsDesktop/readium-sdk/Platform/WinRT/Readium/Readium/Readium.h:37:21: Block pointer to non-function type is invalid

/Users/songsipeng/Desktop/cp/hdsDesktop201605303/hdsDesktop/readium-sdk/Platform/WinRT/Readium/Readium/Readium.h:40:9: Use of undeclared identifier 'ref'

/Users/songsipeng/Desktop/cp/hdsDesktop201605303/hdsDesktop/readium-sdk/Platform/WinRT/Readium/Readium/Readium.h:46:36: No member named 'codecvt_utf8' in namespace 'std'

/Users/songsipeng/Desktop/cp/hdsDesktop201605303/hdsDesktop/readium-sdk/Platform/WinRT/Readium/Readium/Readium.h:57:17: No member named 'Windows' in the global namespace

**Comment by danielweck** [comment]
Hello!
The `WinRT` platform is woefully out of date, not maintained by anyone as far as we know.
PS: this is the `SDKLauncher-iOS` issue tracker, please use the `readium-sdk` repository for other platform-specific issues.
