### ISSUE TITLE
Request a demo that runs normally

### ISSUE THREAD

**Issue by 807276991** [readium/SDKLauncher-iOS#97]
After I open the demo, I will report the error, which is the following:
<img width="611" alt="2017-10-21 8 48 12" src="https://user-images.githubusercontent.com/11973420/31846318-9b6b8c7c-b63c-11e7-935e-d2b124b3e389.png">

: command not found
MakeHeaders. Sh: line 24:
: command not found
MakeHeaders. Sh: line 39: syntax error: unexpected end of file
Command/bin/sh failed with exit code 2

I have been debugging this demo for N days, whether the simulator or the phone is not working, where is the problem?

**Comment by 807276991** [comment]
There is a mistake can't be found ContextFilterLogFormatter. m file, but do have ContextFilterLogFormatter project. m file, is this why?
<img width="1219" alt="2017-10-21 8 52 32" src="https://user-images.githubusercontent.com/11973420/31846359-35aab10a-b63d-11e7-94e2-fae41762841c.png">

**Comment by danielweck** [comment]
You need to initialize all the Git submodules in the https://github.com/readium/SDKLauncher-iOS repository. That's `./readium-sdk` and `./Resources/readium-shared-js`. You can use the following shell command: `git submodule update --init --recursive`. Then make sure to be on the correct Git branches. For example, say you want to build the app from the `develop` branch: `git checkout develop && git submodule foreach --recursive "git checkout develop"` (or simply `cd` inside each submodule repository and invoke `git checkout develop`).
